### ISSUE TITLE
Add some "CRUD on the config. file" operations 

### ISSUE THREAD

**Issue by matro** [buildinspace/peru#102]
Being able to do at least a little bit of basic CRUD of `peru.yaml` would be useful.

This is probably somewhat related to #65, but would apply to a `peru.yaml` file that already exists. Also related to #101.

Would it be feasible for `peru module add` to be a thing, for example?

Say I've got a project (like for example, a WordPress website), and I'm using Peru to manage its dependencies (e.g. the WordPress plugins the site uses). If I need to add a new Peru module for some plugin that needs to be installed in the site, being able to run a command like this would be utterly swoon-worthy magic:

```
peru module add svn wp-foo-plugin wp-content/plugins/foo $url
```

Then I'm just a "`peru sync`, commit `peru.yaml` to my repo, and do whatever other ignore-from-the-repo administrivia" away from nirvana.

 * As a developer, I just need to find the URL of my new dependency, figure out what path to put it at, and interact with Peru.
 * As a SysAdmin, I now stand a chance of writing some scripting glue to keep Peru-managed things like this synced with whatever shenanigans the GUI jockeys do on running instances of the site.

So, `peru module add $type $name $path $url` is rather high on my wishlist (with `peru module list` #101 being on my "I pretty desperately need this" list).

**Comment by matro** [comment]
#101 is totally under this thing's umbrella, but I didn't want to hammer you folks with tickets for each bit of CRUD here. But if I had to choose, I'd wish for #101 above anything else at this point.

**Comment by matro** [comment]
Having Peru be able to write piecemeal to `peru.yaml` would also be a great boost to usability; even for setting up something complex with multiple rules or other advanced things, a relatively simple/natural command like this is a powerful bootstrapper:

 * "Run this command (which could be easily discovered via `peru help` -> `peru module help` docs?), we'll write the `imports:` & `module` boilerplate YAML for you."
 * For extra fanciness, maybe Peru could even validate the path and URL, and even prime the cache?
 * "...But you're on your own with the YAML for the fancy things (here's how to learn more)."
 
Peru already writes to its configuration file with `peru reup`... so some of the plumbing for these capabilities are already in place, right? And `peru override` has some basic CRUD as well.

`peru module remove $moduleName` is hopefully pretty self-explanatory.

Something like `peru module edit $moduleName` would probably be pretty complicated to implement, insofar as the command-line syntax is concerned. It'd make complete sense to me to leave this functionality in the "sorry, ye've gotta edit `peru.yaml` for this" bucket. Witness the complexity of `git config`'s commands.

**Comment by oconnor663** [comment]
I'm hesitant to add this sort of feature. The logic in [`edit_yaml.py`](https://github.com/buildinspace/peru/blob/master/peru/edit_yaml.py) is already approaching black magic, even for the relatively simple demands of reup (adding/editing scalar fields in a well-defined spot). This very minute while writing this, I thought of a case I hadn't tested before, and sure enough it turned out to be [horribly dangerously broken](https://github.com/buildinspace/peru/issues/103). The core problem is that PyYAML is not a "round trip parser": if you read in a YAML file and spit it back out, you lose any comments or formatting that the user put in there. So we have to figure out exactly which characters correspond to the value you're changing, and only replace those. YAML has a lot of corner cases, so this turns out to be error-prone.

We could probably fix all of this with enough code, but I'm also not sure it's a good problem for peru to solve. `peru reup` was a high priority for us, because editing a dozen hashes by hand is so painful, and we can do it all at once. But for the human, I'm not sure typing out a command like

```
peru module add wp-foo-plugin --type=svn --import=wp-content/plugins/foo --url=...
```

is easier than just editing the markup.

It sounds like you're talking about *scripting* a peru workflow, though. In that case, have you considered generating the `peru.yaml` file from other data, rather than trying to edit it in place? Could you tell me more about how you imagine your code being organized? Fun fact that might help: YAML is a superset of JSON, so if you can generate a JSON blob you don't even need a YAML writer.

**Comment by oconnor663** [comment]
Another heuristic we use to think about possible features: Could a separate tool do this just as well as peru could? In the case of `reup`, we need to fetch all sorts of data, and a separate tool would have to reimplement most of peru to do that. But in the case of `module add`, I think it would be the same amount of code whether it was peru doing it or some small script.

**Comment by matro** [comment]
Oy. Had no idea the YAML-writing that was already happen was so scary. I knew YAML had some weird edge-cases to it, but wow.

I guess #65 would still kind of cover the __C__, at least for first-run in a project. And __U__ & __D__... sounds like it's just not worth it with PyYAML. If I can think of any __R__ instances beyond #101, I'll open a new issue for the specific thing.

**Comment by matro** [comment]
For some background, I'm kind of coming at using Peru from two perspectives.

The developers I support would certainly be able to edit the file... but they're also inclined to gravitate to tools like http://wp-cli.org/ when they're available, and we use https://github.com/nvie/gitflow for just about every repo. Experience is telling me that some people do better with longer commands that follow some sentence-like construction, than they do with short commands that require extra cognitive overhead. `git flow feature $verb $name` has had far better uptake than "do `git checkout -b $name`, but only from `develop`, and prefix the branch name with `feature/`" etc, and I've had more work supporting them questions that get answered with "edit this configuration file in this way" than those involving "run this command, and it has a built-in 'help' thing". They're generally more self-sufficient with the latter.

And the shininess of CLIs with tools like Bower and NPM puts pressure on this kind thing here too.

As a SysAdmin, I'm also definitely looking for opportunities to script as many tasks as possible. Once the developers are done with a project, I get to maintain and update everything, which includes sucking down whatever changes a site's admin-users make to it. I can coerce my developers to edit `peru.yaml`, but no way can I get users who know nothing but a GUI to do so, let alone commit those changes. I also make pretty heavy use of tools like https://github.com/interconnectit/Search-Replace-DB that can require some scary-long commands.

I can think of a couple of options for generating/regenerating Peru's YAML that'd fit with my needs here, so this definitely isn't a "you're my only hope!" situation. Especially when making Peru write to parts of a file begs to break the world in fascinating ways.

**Comment by oconnor663** [comment]
I've seen Bower and used NPM a few times, but I'm not really familiar with either of them. Can you tell me more about the commands they include that work well for you?
