### ISSUE TITLE
pick and export don't seem to interact the way files and export did

### ISSUE THREAD

**Issue by kergoth** [buildinspace/peru#104]
It seems that the path specified to pick is not relative to the exported path, whereas files was. I'm now having to make heavy use of `move` to work around this.

**Comment by oconnor663** [comment]
You described it right. The goal is that if before you had

```
export: foo
files: bar
```

you should now do this:

```
pick: foo/bar
export: foo
```

That is, `pick` requires a full (pre-export) filepath, but `export` will still trim the picked path to give you the same result you were getting with `files`. Can you tell me more about what you were doing with `move`? It sounds like you were thinking of a different model of how `pick` worked, so hopefully I can improve the docs to clear things up.

Note that the order of operations is always 1) `copy`/`move`, 2) `pick`, 3) `executable`, 4) `export`, 5) [deprecated] `files`. The order that you write the fields in your module doesn't matter, because YAML turns the whole thing into an unordered map, but I recommend this order for clarity. It might be a good idea for us to emphasize the order of operations in the docs, if that makes it clearer how the other fields relate to `export`.

To explain why we made the change -- actually I have to take the blame for this one, since @olson-sean-k preferred a different design -- the reason for the switch from export-relative paths (used in `files`, going away soon) to full paths (used in `pick`), is for consistency with other new fields. The `copy` and `move` fields have to take a full path and apply before the `export` step, otherwise you wouldn't be able to move outside files into the export directory. If other fields applied after the `export` step and took short paths (like `files`), you'd have a confusing mix of different path types in the same module. Making everything take full paths seems to be the simplest thing to do, though it means more typing when you write the file. Let me know if this seems like a bad design choice.

**Comment by oconnor663** [comment]
Ah ok, I'm looking at the [`peru.yaml` in your dotfiles](https://github.com/kergoth/dotfiles/blob/master/peru.yaml), and now I think I understand your question better. You're using `move` and `pick` to get the same effect as `pick` and `export`, but I think it'll work just fine if you do it like the example above.

By the way, looking at your comment for the `smem` module, what's the bug you ran into? When I build a test project with just that module, it seems to work ok for me.

**Comment by kergoth** [comment]
Ah! That makes sense, thanks for the explanation. I do prefer the new design, given that it seems to require less knowledge of peru's internal behavior (order of operations), letting it be a more purely declarative format. I appreciate your quick response on this.

Regarding smem, I hadn't had time to open an issue yet, as I wanted to do more investigation to determine if it was truly a peru bug. It seemed related to use of the particular hg modules I'm using, coupled with `reup`, and possibly also bound to use of the virtualenv I was using for peru. For some reason, hg was complaining about 'obsolete' markers, and peru would pick up 'obsolete' as the new rev. That said, I'm no longer able to reproduce this, so ignore me, and I'll open a new issue if I ever manage to make it happen again. Thanks again.

**Comment by oconnor663** [comment]
Oh weird. I wouldn't be surprised if hg reup had some corner cases, so don't hesitate to file another issue if you see it again.

**Comment by oconnor663** [comment]
Thought about it more, and I bet I know why it's happening. See #105. Please do let me know if you can repro it.
