### ISSUE TITLE
add a warning for modules with duplicate names

### ISSUE THREAD

**Issue by mitchtbaum** [buildinspace/peru#107]
I would like to import multiple modules to a common import directory and have each one stored individually in a folder named with its repository name.

A similar scenario is like when you untar ```foo.tar``` and it saves its contents to ```foo/```, and when untarring multiple tarballs in a common directory you get a folder for each untarred archive.

I did a simple test with this config below and it resulted in a nested import dir, called ```*```, which I found odd, because ```mkdir *``` fails.

```
imports:
  plugin: plugins/*

git module plugin:
  url: https://github.com/mitchtbaum/pelican_reference
```

With this config, instead of merging both modules (intelligently or even with collisions), only the last item specified for that output location will show up:

```
imports:
  plugin: plugins/

git module plugin:
  url: https://github.com/rdegges/pelican-minify

git module plugin:
  url: https://github.com/mitchtbaum/pelican_reference
```

**Comment by oconnor663** [comment]
#### Multiple modules with the same name

You If you have multiple modules named exactly the same thing, one of them will override the other, just like you're seeing in your example. This is happening because the YAML file gets parsed into a dictionary, and dictionaries can only have one value for a given key. Unfortunately, as far as I know, there aren't any YAML parsers for Python that can recognize this error and report it; the one we use just silently overwrites the first value with the second. Because of all that, you always have to give your modules different names.

To help other people hitting the same problem, I think we should do this: After we parse everything out and get the module and rule names, read through the file and see if there's just more than one line that starts with that full name (e.g. `git module X`). If we find more than one, we can print a helpful warning.

#### Importing several modules to the same place with their own subdirectories

The way peru interprets import paths is that the *contents* of a module go at that path. No extra subdirectory is created other than what you put in the import path yourself. So (including the fix above about using different module names) you might want your `peru.yaml` file to look something like this:

```
imports:
  minify-plugin: plugins/minify
  reference-plugin: plugins/reference

git module minify-plugin:
  url: https://github.com/rdegges/pelican-minify

git module reference-plugin:
  url: https://github.com/mitchtbaum/pelican_reference
```

Note the explicit `minify` and `reference` directories in the import paths. As you've noticed, when you leave that off, files go straight into the `plugins` directory. (Sometimes this is useful, like when a module is just one file.)

#### Other questions you kinda sorta alluded to

**Why does the \* end up in the directory name in the first example?** Stars don't have any special meaning in the import path, so they're interpreted as a character in the path just like any other. (Note that stars are special in some other fields, like `pick`.) Imports are always written with one module name on the left, and one path on the right.† The reason that `mkdir *` doesn't seem to work is that the shell always interprets stars specially, so if you want to create a directory with stars in the name, you need to do something like `mkdir '*'`.

**How does peru merge files when two imports conflict?** It doesn't; this is always an error. In fact it's also an error when imports conflict with other files that peru didn't even create. Better to be safe and fail fast.

**Does tar create a directory for each archive you unpack?** Surprisingly no, tar doesn't necessarily do that. Tar will create a subdir if the files in the tarball say they belong in that subdir, but it can also dump a bunch of files into the current directory. (That's called a ["tarbomb"](http://en.wikipedia.org/wiki/Tar_%28computing%29#Tarbomb), and it's considered very bad manners.) 

† I lied :) You actually can import one module in multiple places, by putting a YAML list of paths on the right instead of a single path. But that's undocumented and usually not what you want, and in any case it still doesn't work with stars.

**Comment by oconnor663** [comment]
Thought about this a little more. The duplicate names thing is a problem for all dictionaries, not just the top-level list. So for example, if someone gives multiple `url` fields in a git module, one of them will just overwrite the other. It would be nice to have a warning that catches this case too.

Here's what I'm thinking now:
1. Scan the YAML file line-by-line, keeping track of the indentation level.
2. Look at the whitespace-trimmed text of each line up to the first colon.
3. If the same text occurs twice at the same indentation level, without a line in-between of lesser indentation, print the warning.

There are probably some ways to write legitimate YAML that would confuse this check, but it's just a warning, so it shouldn't break anyone. And there are ways to hit this bug without triggering the warning, like using JSON-style inline dictionaries, but presumably those people know what they're doing :)

**Comment by mitchtbaum** [comment]
@oconnor663:  My main challenge to present to you is for a way to have each module by declaring it in only one location.  Managing both import path and module name in tandem would be a significant burden, especially as this list reaches into 10's and 100's of entries.  Automating updates to this list would also be easier with reusable imports.

Perhaps a ```plugin: plugins/{$repo}``` syntax would be feasible?

**Comment by oconnor663** [comment]
@mitchtbaum, take a look at https://github.com/buildinspace/peru/issues/54, and add your thoughts there.
