### ISSUE TITLE
How to reup and sync single module?

### ISSUE THREAD

**Issue by enzochiau** [buildinspace/peru#118]
My scenario is:  (peru v0.2.2)

I have two modules managed by peru (M1, M2). Now I modified one some files in imported M1 for quick test. Now I hope to update M2 to the latest revision.

Is it there any way to do that?

**Comment by oconnor663** [comment]
Reup works just fine on a single module. You can run

    peru reup M2 [--nosync]

By default (without that `--nosync` flag), peru will run a sync after the reup, and that sync will fail because of your modified files. Right now the only way to get around that is to use the `--force` flag, which will erase your edits in M1. I've though a little bit about allowing you to sync a single module from the command line, but there's no code for that right now. (One open question: if you run the "sync only M1" command, does that mean that M2's files should disappear, or should they be left in place unchanged?)

The supported way to make edits to a module without losing the ability to sync, is to use the `override` command. Have you taken a look at that?

**Comment by enzochiau** [comment]
Let me answer the open question:

When `sync only M1`, the M2's files should keep unchanged.

About the `override`, I give it a try. But I think that can do the work but which much more effort. To archive what I want, I have to have a clone of M1 in somewhere else. Pull the cloned M1 and then do `sync` in my peru project.

**Comment by oconnor663** [comment]
The goal of `override` is that, if you put `peru sync` in your `Makefile` or your `run.sh` or whatever you use to run your repo, it will do the right thing. Agreed it's a little annoying if you run `peru sync` by hand.

**Comment by oconnor663** [comment]
I'm going to close this one, because it's been a while, but feel free to reopen it to discuss more. One of the things we've managed to avoid so far is different "modes" of syncing, or even the concept of checking to see whether you're synced. Instead, there is simply `sync`. I don't know if we'll be able to keep it that simple forever, but as long as we can get away with it I think it's a good thing.
