### ISSUE TITLE
"UnicodeEncodeError: 'ascii' codec can't encode character" on peru sync

### ISSUE THREAD

**Issue by oryband** [buildinspace/peru#136]
Using peru in a docker image, with `python3` and `git` packages installed via *virtualenv* yields the following result:
```python
(peru)root@7ccee9c73fb8:~/# peru sync
Exception in callback None
handle: <TimerHandle cancelled when=85353.65284133301>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/root/peru/lib/python3.4/site-packages/peru/display.py", line 158, in _draw
    self.output.write('\u250c' if len(self._job_slots) > 1 else '\u2576')
UnicodeEncodeError: 'ascii' codec can't encode character '\u2576' in position 0: ordinal not in range(128)

# this error is repeated multiple times, i truncated for easier reading
```

**Comment by oryband** [comment]
@ofir-petrushka

**Comment by oconnor663** [comment]
I think this error is happening when peru wants to print fancy unicode bracket characters, like this:

```
┌ a
├ b
└ c
```

The immediate workaround is to run peru with `-q`/`--quiet` or `-v`/`--verbose`, so that it stops trying to be fancy. Quiet is also the default if peru is running with its stdout redirected to a file.

It sounds like your terminal is configured in ASCII mode, without Unicode support. If you run

```bash
python3 -c "import sys; print(sys.stdout.encoding)"
```

does it say ASCII?

If you run

```bash
python3 -c "print('日本語')"
```

does it fail with the same error?

**Comment by oryband** [comment]
i'm using urxvt, which supports unicode

**Comment by oconnor663** [comment]
Oops, I should've predicted copy/paste wouldn't work there. I bet you can repro the error with this:

```bash
python3 -c "print('\u65e5\u672c\u8a9e')"
```

It looks like `ANSI_X3.4-1968` is what Python falls back to when the system locale is bad. It's what I see on my own system if I run `LANG="foo" python3 -c "import sys; print(sys.stdout.encoding)"`. (Normally without messing with `LANG` I see `UTF-8`.) Is it possible you have a misconfigured `/etc/locale.conf` or something like that? Or was your system intentionally set up to be ASCII-only?

Ultimately I'm not sure what the Right Thing for peru to do is here. It would be easy enough to avoid printing our own unicode brackets when a terminal is in ASCII mode, but we'd still have to worry about unicode in git URLs, for example. Do you know if this is something that other Python tools explicitly handle? Maybe there's a hack we can use to tell Python to just emit UTF8 anyway?

**Comment by oconnor663** [comment]
Could you please let me know what docker image you're using? I could take a look at the locale configs myself.

**Comment by oconnor663** [comment]
It looks like exporting `PYTHONIOENCODING="utf8"` is another workaround for this, which you might prefer over `--verbose` or `--quiet` if you expect a person to be watching the terminal output from your docker.

**Comment by oryband** [comment]
@oconnor663 maybe this should be set internally in peru? is that even possible? asking the user to do that manually feels wrong. If not possible, at least add this to the docs.

**Comment by oryband** [comment]
adding a link to that article is also a good idea

**Comment by oconnor663** [comment]
Agreed, I think fixing it under the covers would be the right thing to do. I'm not sure how easy that will be though, because I think this setting might get locked in early in interpreter startup, before any of our code has a chance to run? If we have to do some hack where we replace the global stdout and stderr pipes, I'd be worried that'll break some random system. I need to do some googling.

**Comment by oconnor663** [comment]
@oryband could you please confirm that that change fixes the issue for you? The easiest way is to checkout that commit in your container and then run `pip install .` from the root of the repo.

**Comment by oryband** [comment]
actually, i can't. i already avoided this bug
i think i reproduced it by using a bad `peru.yaml` file with a bad `imports` section
when executing `peru sync`, i saw this bug. don't remember why

i also already added the locale fixed to the docker image i was running this from, so this also bypasses the problem

sorry :\

**Comment by oconnor663** [comment]
No worries. I think the most common way someone would hit this would be to do a `peru sync` inside an interactive docker shell, so that we default to fancy formatting and then choke on the `├` etc. fancy characters. This fix seems to work for at least that case, so I'm guessing it works for the rest.

**Comment by oryband** [comment]
very well then. if you feel this has been resolved, feel free to close this issue.

**Comment by oconnor663** [comment]
Note to self: The default Windows terminal encoding seems to be [cp437](https://en.wikipedia.org/wiki/Code_page_437), which also causes these problems. We might need to handle more than just ASCII mode...

**Comment by oryband** [comment]
@oconnor663 this might also be a solution (please verify):
```python
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by oryband** [comment]
http://stackoverflow.com/questions/3828723/why-we-need-sys-setdefaultencodingutf-8-in-a-py-script

**Comment by oconnor663** [comment]
That fix looks like it's Python-2-only I'm afraid.

Since I don't have any better ideas, I've gone ahead and landed the hack above (https://github.com/buildinspace/peru/commit/a8072aa2be9fb9436d0bb0b76c9331e3b71011d9) and pushed release 0.2.6. Hopefully this won't break anything!

**Comment by oconnor663** [comment]
Thanks for your help throughout all this, by the way!

**Comment by oryband** [comment]
happy to help
