### ISSUE TITLE
revisit automatic recursive fetching

### ISSUE THREAD

**Issue by oconnor663** [buildinspace/peru#146]
That might actually interact badly with Makefiles that call `peru sync`. Does anyone actually use recursive modules?

**Comment by matro** [comment]
I've thought about trying to use them, yeah... however!... the idea makes me a little nervous, so I haven't tried.

Most of my Peru uses have been things involving `pick` (where recursive modules wouldn't be applicable) or using some "stable" release channel for a module's URL, where any of that module's own dependencies are already pre-populated (by their own build/release process, whatever it is). I don't know if this is necessarily _technically_ true, but if _feels_ safer to me to be fetching tarballs or something than to have a tree of `peru sync`s that might fail because someone _else's_ `peru.yaml` went stale to link-rot.

I guess my opinion more or less comes down to "recursive modules sounds neat in theory, but high-risk in practice".

And having Peru play well with Makefiles is pretty high on my needs list, FWIW.

**Comment by oconnor663** [comment]
To clarify the situation I'm worried about:

1) You put `peru sync` in your Makefile.
2) I depend on you, and import your project in my `peru.yaml`.
3) Because I depend on your build artifacts, I also call your `make` (in addition to `peru sync`) from my Makefile.

Now I'm going to run into a conflict. When my build tries to run *your* `peru sync`, it's going to yell and fail, because *my* peru sync has already laid out all your files.

This might be related to why `git clone --recursive` and `git submodule init --recursive` are not the defaults...

**Comment by matro** [comment]
Ah, I think I see what you're saying. Much more concise and sense-making than what I was trying to say. I _definitely_ worry about that situation. It makes me careful about what I choose to use for modules, and hesitant to even think about setting myself up for this, even when I control all the repos involved.

I haven't messed at all with recursive `peru.yaml`s yet, so I wouldn't know... is recursing like this Peru's default?

If it is (or becomes) non-default, would it make sense to leave it as an opt-in kind of thing? Maybe as a per-module setting in `peru.yaml`?

**Comment by oconnor663** [comment]
It is currently the default, yes.

It also occurs to me the recursive modules might violate the intent of syncing specific revisions. If you pick a commit in your upstream, but your upstream has a peru.yaml file with unversioned dependencies, then some part of your dependencies will also be unversioned. Not ideal.

**Comment by oconnor663** [comment]
My current plan: We will turn recursion off be default, and add a new `recursive` field that takes a boolean applies to all module types.

What I'm going to do right now: We don't actually support boolean fields in `peru.yaml`. I'm going to add that in and define the `recursive` field, but I'm going to default it to `true`. I'll also add a printed warning in that codepath about how the default is going to change in the future, and link to this issue.

**Comment by oconnor663** [comment]
The change in the default has landed in master. I'll give it "some amount of time" for the warning-only release to filter out to people before I make a new major release including this change.

Note that another benefit of no-recursion-by-default is that we're much less likely to cause confusing problems like https://github.com/buildinspace/peru/issues/128.

**Comment by oconnor663** [comment]
Went out with 0.4.0.
