### ISSUE TITLE
simple peru configuration fails in checkout_subrepos 

### ISSUE THREAD

**Issue by nezhinsky** [buildinspace/peru#157]
ubuntu 15.10
peru version 0.4.0 installed using `pip install`

peru.yaml :
```
imports:
    accelio: accelio/
    tgt: tgt/

git module accelio:
    url: https://github.com/accelio/accelio.git

git module tgt:
    url: https://github.com/fujita/tgt.git
```

produces the following output (after cloning both directories)
```
In target "accelio":
  git plugin exited with error code 1.
  Fields:
      url: https://github.com/accelio/accelio.git
  Output:
  git clone https://github.com/accelio/accelio.git
  Cloning into bare repository '/home/alexn/peru_test/.peru/cache/plugins/git/7618d8b14ee803349db6606890b1522513f62900/00f35ba5502eaaab23c66cabe0d173f9a37ee8f5'...
  remote: Counting objects: 15824, done.        
  remote: Total 15824 (delta 0), reused 0 (delta 0), pack-reused 15824        
  Receiving objects: 100% (15824/15824), 10.45 MiB | 1.45 MiB/s, done.
  Resolving deltas: 100% (11389/11389), done.
  Checking connectivity... done.
  git fetch https://github.com/accelio/accelio.git
  Traceback (most recent call last):
    File "/usr/local/lib/python3.4/dist-packages/peru/resources/plugins/git/git_plugin.py", line 134, in <module>
      plugin_sync()
    File "/usr/local/lib/python3.4/dist-packages/peru/resources/plugins/git/git_plugin.py", line 121, in plugin_sync
      checkout_tree(URL, REV, os.environ['PERU_SYNC_DEST'])
    File "/usr/local/lib/python3.4/dist-packages/peru/resources/plugins/git/git_plugin.py", line 100, in checkout_tree
      checkout_subrepos(repo_path, rev, dest)
    File "/usr/local/lib/python3.4/dist-packages/peru/resources/plugins/git/git_plugin.py", line 116, in checkout_subrepos
      sub_rev = ls_tree.split()[2]
  IndexError: list index out of range
```

code where the error occurs:
```
        ls_tree = git('ls-tree', '-r', rev, sub_relative_path,
                      git_dir=repo_path, capture_output=True)
        sub_rev = ls_tree.split()[2]
```
I checked that `ls_tree` is empty, which causes the error in unguarded `split()`

**Comment by oconnor663** [comment]
Good catch, and a very detailed report, thanks!

I'm pretty sure the fix is going to be checking the length of `ls_tree.split()`, just like you mentioned, and then skipping that submodule. What I'd like to figure out if I can, though, is how the https://github.com/accelio/accelio repo got into the state it's in.

Normally when you add a submodule, git puts two things in your repo: an entry in the `.gitmodules` file, and also a submodule object at the place in the tree where your submodule will go. (In an actual checkout this submodule object becomes an empty directory before initialization, and then a full clone after.) You can see this in the [YouCompleteMe repo](https://github.com/Valloric/YouCompleteMe), where the [paths in the `.gitmodules` file](https://github.com/Valloric/YouCompleteMe/blob/master/.gitmodules#L2) correspond to these [visible submodule objects](https://github.com/Valloric/YouCompleteMe/tree/master/third_party) in the tree.

Accelio seems to have gotten into a state where it [has a `.gitmodules` entry](https://github.com/accelio/accelio/blob/master/.gitmodules#L2) but [no corresponding submodule objects in the tree](https://github.com/accelio/accelio/tree/master/src/kernel/compat). Do you know how that might've happened? Maybe someone did something weird by hand? It's simple enough to detect this case and ignore it, but I want to make sure that's the right thing to do.

Update: Ok, I think I figured out how they ended up that way: https://github.com/accelio/accelio/issues/113. I'll go ahead with the fix.

**Comment by oconnor663** [comment]
As a side note, I should probably define a way to disable git submodule fetching. Right now there's no workaround for this.
