### ISSUE TITLE
Use `sha1sum` to detect changes

### ISSUE THREAD

**Issue by loveencounterflow** [buildinspace/peru#186]
I have a workflow where I develop a 'guest' project that lives in a subfolder of a 'host' project. When I want to make changes in the guest, it is much easier and straightforward to not do them in the guest's original repository but right in the subfolder within the host; that way, a test run immediately shows me whether my updates work. I then use a diff/merge tool (`meld`) to merge all changes back into the guest's repository, from where I commit and push to remote. 

At that moment in time, the contentent of the referenced guest repo and the contents of the guest subfolder are 100% identical. Sadly, when I then do `peru reup`, `peru` will complain that 'imported files have been modified', which is sort of true and sort of false. It's true that I did touch those files, but their contents are bit-identical with the ones that peru will only import with `--force`. IMHO this is questionable behavior; if I want to do `cp A B` but avoid to overwrite changes, then, clearly, when `sha1sum A` equals `sha1sum B`, I can totally do or not do `cp A B` (the only difference being possibly the file dates on `B`). At any rate, it should *not* cause `peru` to abort as no content changes will be effected either way.

My suggestion is to first check both the new and the old files' `sha1sum`s, and never opt out when both are identical.

**Comment by oconnor663** [comment]
I thought about this a little when we were first coding the `sync` rules, and the reason I chose what we have now is that I'm a little worried about peru implicitly "taking ownership" of your changes. For example, consider the following flow:

1. I do a `peru reup`, and it pulls in some new line X in one of my dependencies, which breaks something.
2. I manually delete X to see what happens without it. My peru files are now dirty.
3. I checkout an older commit to do more testing. I run `peru sync`, maybe just as part of my test scripts.
4. I checkout the latest commit again, and `peru sync`.

There are two different things that could happen in this flow. With the current behavior, step 3 is an error, because I've edited dependency files relative to the _last version that was synced_. But if we change the current behavior in the way you're describing, perhaps step 3 will work, if line X was the only difference between the old dependencies and the new ones. That means that in step 4, `peru sync` will _undo_ my deletion of X. Essentially, peru "forgot" that that change was "mine" in step 3.

This is a kind of trivial example, but I worry it could lead to surprising behavior under the right conditions. Since the `--force` flag is a relatively clean way to make this work today, I lean towards keeping the current defaults.

I'm also curious whether you've tried a workflow based on `peru override`. An "edit dependencies in place" workflow is by far the most commonly requested feature, but it's also one of the very first things we decided _not_ to do with peru, because it gets very complicated very quickly. The override mechanism fits more cleanly into peru's model, and I'm curious whether it might work for you.

**Comment by loveencounterflow** [comment]
Thanks for your detailed answer. I do not claim I fully understand your scenario, though. 

A year ago or so I was on the brink of writing a dependency resolution module myself and I'm now happy that it went quickly over my head and I never came around to actually doing it. What that stint taught me tho is that file modification dates are a relatively poor proxy for like anything; on the one hand, there are file systems with a granularity of one entire second (OSX HPFS used to be among them), and on the other, a mere `touch`-like action can make a file look arbitrarily new anytime (not to speak of the vagaries that come with unpacking from archives or explicit setting of dates to the past or future). 

Hence, I've come to use file dates only as cheap excuse or last straw; the only real thing to me is file contents. I fully understand that Peru does and should resist the urge to manage in-situ dependency edits or do merges, with or without supervision. But this is not my point; my suggestion is to obtain a `sha1sum` from each file in the newly obtained (or cached) copy of the guest project, and then check each of those content hashes against those in the already installed copy of the guest. A correspondence of all hashes cannot possibly allow for any undetected change in the installed copy.

BTW I just tried and deleted a file from an installed guest copy, then did `peru reup`, and voila, I did get it back without even a notice; I gather this is the intended behavior. But then I did `touch` that same file, and `peru reup` ran without complaints. Then I changed one character (Peru complains) and changed it back (Peru is silent). Tried the same with a minimally updated guest version in the repo, same. Now I'm confused, because hours ago I did an `sah1sum` on each of the files in question, and they were source-identical, and yet Peru complained. That looked like file dates being to new, but the experiment I did as I'm writing this would indicate otherwise.
