### ISSUE TITLE
How to use `override`?

### ISSUE THREAD

**Issue by loveencounterflow** [buildinspace/peru#187]
In the discussion of #186 I learned that `peru override` is the way to go when you want to develop an included ('guest') project from an including ('host') project; seen from the file layout, this would look like

```
guest-repo/
  .git/
  somefile
  ...
host/
  peru.yaml
  guest-copy/
    somefile
    ...
  ...
```

The readme only states that `override` "Replace[s] the contents of a module with a local directory path, usually a clone you've made of the same repo. This lets you test changes to imported modules without needing to push your changes upstream or edit `peru.yaml`." which leaves me puzzled how to organize my workflow. 

I'd greatly appreciate any help here because what I'm doing now is editing files in my local copy (`host/guest-copy/somefile`), seeing that the changed guest code works in the intended habitat, and then use `meld` to shuffle changes back to the guest repo (`guest-repo/somefile`). Clearly, that's less than ideal.

**Comment by oconnor663** [comment]
Sorry for not having any examples of this available. Maybe by thinking about your workflow together, we can come up with a good example and add it to the docs?

The idea is that you would run:

    # `guest` is whatever you named your module in peru.yaml
    peru override add guest ../guest-repo

Then you make your edits in `guest-repo/somefile`, and you rerun `peru sync` in your `host` project to pull them in. Rather than fetching the latest commit from`guest`'s GitHub url (or whatever), `peru` will just read whatever files are sitting at the `../guest-repo` path.

Running `peru sync` manually to pull in the changes can be a little bit annoying. However, the goal is that it should be easy to integrate `peru` into whatever script or testing command you were about to run afterwards. So for example, if you normally call `make test` in your `host` repo after you've pulled in changes, you might consider putting `peru sync` at the top of the list of commands that `make test` runs. (Some [more interesting integrations with `make`](https://github.com/buildinspace/peru/tree/master/docs/make_examples) are possible too.)

**Comment by loveencounterflow** [comment]
I'm doing exactly as you say as I'm writing this, so give me a few hours before I come back to you with my experiences in this new way of doing this. I guess I will be able to live with the extra sync step; after all, I can always do `peru sync && run-host-tests` so I don't have to, erh, manually think about that each time I run a test. It's definitely great if I can avoid the roundtrip to and from the guest repo, b/c apart from being several extra steps in different folders, it also means a lot of nonce commits (i.e. commits that happened before testing and have to be fixed or amended or whatever). 

BTW my guest repo here is https://github.com/loveencounterflow/intershop, and when you look at the commit history you'll see it has already suffered from a lot of `update` and `pull in changes from m3`, so I'm glad to find a way to avoid both wholesale and nonce commits as far as feasible).

Totally OT but just want to add that reading about how to build things and do stuff with peru I started to look into makefiles, first time of all. I must say tho I'm totally aghast as for the syntax of makefiles as well as all the built-in silent assumptions and the dirty tricks you have to play to make non-file targets work, the lack of `if`/`else` branching in the original version that later caused conflicting standards, and and and. I've since re-discovered `rake` for doing everything that peru can't, won't and shouldn't provide, and I'm quite happy with it.

**Comment by oconnor663** [comment]
OT: I'm convinced that the future is going to be something like [Bazel](https://bazel.build/) or [Buck](https://buckbuild.com/), but yeah, making a general purpose build tool is really hard. There are a lot of ways in which it's easier than it used to be (standardized formats like JSON/YAML/TOML are huge), but also the tools are expected to do more (run tests, compile docs, package for Android/iOS). It's hard to hit a sweet spot where your tool is being really helpful, without forcing projects to be organized some very specific way that not everyone likes.
