### ISSUE TITLE
The git plugin needs to handle relative submodule URLs

### ISSUE THREAD

**Issue by parceltb** [buildinspace/peru#200]
I have a peru.yaml file of the format:

``` yaml
imports:
    boost: external/boost/

git module boost:
     url: https://github.com/boostorg/boost.git
     recursive: true
````

But running peru sync yields the following result:
```shell
In target "boost":
  git fetch https://github.com/boostorg/boost.git
  git clone ../system.git
  fatal: repository '../system.git' does not exist
```

A simple git clone --recrusive on the boost repo works, however:

```shell
git clone --recursive https://github.com/boostorg/boost.git

Cloning into 'boost'...
remote: Enumerating objects: 231616, done.
remote: Total 231616 (delta 0), reused 0 (delta 0), pack-reused 231616
Receiving objects: 100% (231616/231616), 59.11 MiB | 13.42 MiB/s, done.
Resolving deltas: 100% (147759/147759), done.
Checking connectivity... done.
Submodule 'accumulators' (https://github.com/boostorg/accumulators.git) registered for path 'libs/accumulators'
Submodule 'algorithm' (https://github.com/boostorg/algorithm.git) registered for path 'libs/algorithm'
<MORE>
```
Maybe I am just mis-understanding how to use the utility, but this seems like it would be the correct use.  If not, if you could point me in the right direction, that would be great, otherwise, seems like an issue.

**Comment by oconnor663** [comment]
Note that `recursive: true` is for repos that contain their own `peru.yaml` files, not for git submodules. Those should be fetched by default, no special flags required. That said, I'm not sure what's causing this failure -- there might be a big in the git submodules code here. I'm abroad this week, but I'll try to look into it.

**Comment by parceltb** [comment]
I see, that makes more sense then.   No real rush though at when to look into it - for the time being I'm just checking it out manually.

**Comment by oconnor663** [comment]
Very interesting! It looks like the issue here is that Boost uses a git feature I didn't know existed. Take a look [at this line in `.submodules`](https://github.com/boostorg/boost/blob/master/.gitmodules#L3):

    [submodule "system"]
        ...
        url = ../system.git
        ...

That's saying that the URL for the `system` submodule is *relative to* the upstream URL of the parent repo. Peru has no idea that this is a thing, so it's trying to clone `../system.git` as a raw path, which fails. I'll need to add support. It looks like it should be reasonably straightforward. (Actually it seems like this might be more straightforward for peru than for git, because peru knows exactly what URL was used to clone the parent, but I'm guessing that git has to assume that the `origin` remote is the one that was used? And if there is no origin at all then nothing works? I'm not sure.)

**Comment by oconnor663** [comment]
From the git docs, https://git-scm.com/docs/git-submodule:

> <repository> is the URL of the new submodule’s origin repository. This may be either an absolute URL, or (if it begins with ./ or ../), the location relative to the superproject’s default remote repository (Please note that to specify a repository foo.git which is located right next to a superproject bar.git, you’ll have to use ../foo.git instead of ./foo.git - as one might expect when following the rules for relative URLs - because the evaluation of relative URLs in Git is identical to that of relative directories).

**Comment by oconnor663** [comment]
Indeed, if you `git remote remove origin` and then try to sync submodules, you get this

    warning: could not look up configuration 'remote.origin.url'. Assuming this repository is its own authoritative upstream.

followed by a bunch of errors. Again, peru shouldn't need to worry about this part, because peru always has a location for any given module.

**Comment by oconnor663** [comment]
Here's the relevant logic in git itself: https://github.com/git/git/blob/v2.20.1/builtin/submodule--helper.c#L135

**Comment by oconnor663** [comment]
@parceltb could you check that the fix in https://github.com/buildinspace/peru/pull/201 works for you? You can run peru directly out of the repo with the `peru.py` script in the repo root.

**Comment by parceltb** [comment]
@oconnor663 Wow!  That was a really interesting  issue, I had literally no idea git had that feature either!
Sorry for all of the delays in getting back by the way, and I got a chance to test it, and it works like a charm now!

I seriously can't thank you enough for the prompt responses and for fixing this so quickly.

**Comment by oconnor663** [comment]
The fix is in master, and we'll release it shortly. The only question left is, what should the new version be. We're bumping the minimum supported version of Python to 3.5 (an unrelated deprecation prior to this fix), and I'm not sure if that's kosher to go out in a patch version bump. I've [asked on reddit](https://www.reddit.com/r/Python/comments/a7s5co/im_bumping_the_minimum_supported_python_version/), but also let me know what you think. @olson-sean-k too.

**Comment by parceltb** [comment]
@oconnor663 @olson-sean-k It doesn't really matter to me, however I agree with the argument that it shouldn't be a major bump.  To me, only major feature changes themselves (i.e. usually interface/interaction-based changes, or substantial feature improvements) warrants the major version bump.

That being said, did Peru support Python 2.x.x originally?  If so, and the changes drop Python 2.x.x, then I would agree with the major bump.  If it only supported 3.x.x to begin with, and now only requires a larger major version, then again, I would default to the minor version bump.

**Comment by oconnor663** [comment]
Alrighty, a minor version bump it is.
