### ISSUE TITLE
Import error when running from a venv

### ISSUE THREAD

**Issue by jbrubake** [buildinspace/peru#238]
I used `pipx` to install `peru` in a venv. `peru` runs the `git module` properly but the `curl module` fails. Specifically the `import peru.main` at line 13 in `peru/resources/plugins/curl/curl_plugin.py` fails

To test, I installed `peru` using `pip` but not inside a venv and it works fine so its either something weird that `pipx` is doing, or the venv in general

**Comment by maxwell-k** [comment]
I am new to peru and a long time user of pipx. peru looks really promising and pipx is brilliant. It would be super to get them working together.

<details>
<summary>Reproducing the issue</summary>

Start with a cut down version of the example in the README:

    imports:
        pathogen: .vim/autoload/

    curl module pathogen:
        url: https://codeload.github.com/tpope/vim-pathogen/tar.gz/v2.3

Make sure `~/.local/bin` is on the current PATH

Install `pipx`

    mkdir --parents ~/.local/bin \
    && curl -Lo ~/.local/bin/pipx https://github.com/pypa/pipx/releases/download/1.2.0/pipx.pyz \
    && chmod u+x ~/.local/bin/pipx

Install peru using pipx:

    pipx install peru

Make sure git is installed

Try to sync:

    peru sync

The error message is:

    In target "pathogen":
      Traceback (most recent call last):
        File "/home/maxwell-k/.local/pipx/venvs/peru/lib64/python3.11/site-packages/peru/resources/plugins/curl/curl_plugin.py", line 13, in <module>
          import peru.main
      ModuleNotFoundError: No module named 'peru'

I reproduced this on Fedora 38, so Python 3.11.

</details>

I believe this issue relates to the [plugin architecture] for peru. IIUC peru plugins are executable files; for this issue `curl_plugin.py` is the relevant plugin.

If I install peru with [pipx]; then pipx sets up a virtual environment and installs peru there. pipx adds a symbolic link to the peru command from that virtual envinronment to the PATH. Continuing the example above, the [shebang] line is:

    #!/home/maxwell-k/.local/pipx/venvs/peru/bin/python

However the shebang line for `curl_plugin.py` is:

    #! /usr/bin/env python3

This means that `curl_plugin.py` is executed by a Python interpreter that does not have the peru package installed. That explains the error message!

@oconnor663 is support for pipx something you would consider?

Thank you for your work on peru!

If anyone has suggestions for an implementation perhaps I can start on a PR. I'm not very familiar with the peru code; one option might be to switch to an entry point for `curl_plugin.py` so that pipx will update the shebang line.

<details>
<summary>Workaround</summary>

As a workaround is to manually change the shebang line for `curl_plugin.py`, for example:

    cd ~/.local/pipx/venvs/peru/lib/python3.11/site-packages/peru/resources/plugins/curl \
    && mv curl_plugin.py curl_plugin.py.bak \
    && head --lines=1 ~/.local/bin/peru > curl_plugin.py \
    && tail --lines=+2 curl_plugin.py.bak >> curl_plugin.py \
    && chmod u+x curl_plugin.py

This change will be lost on any subsequent upgrade. It also makes installation of peru with pipx more complex. Support for installation with pipx would be ideal. I appreciate that this is open source and maintainers and contributors are volunteers. Thank you for reading!

</details>

[pipx]: https://pypa.github.io/pipx/
[plugin architecture]: https://github.com/buildinspace/peru/blob/master/docs/architecture.md#plugins
[shebang]: https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by maxwell-k** [comment]
Turns out there was a much easier fix than I expected; I've opened a pull request. 

To test the proposed fix using the steps to reproduce above; in place of using `pipx install peru` to install peru, try:

    pipx install git+https://github.com/maxwell-k/peru

Or if you prefer to run sync directly:

    pipx run --spec=git+https://github.com/maxwell-k/peru peru sync

**Comment by mochaaP** [comment]
cc @oconnor663 - can you take a look at this?

**Comment by oconnor663** [comment]
If I understand the issue correctly, `pipx` is installing the `peru` module in a sandboxed directory, so when `peru` shells out to plugin Python scripts, those interpreters don't see the `peru` module. When I try it on my box, `PERU_REEXEC_PYTHON=always` fixes the problem. I wonder if we should just make that the default behavior on all OSs (currently it's the default on Windows only).

**Comment by oconnor663** [comment]
I've made `PERU_REEXEC_PYTHON=always` the default everywhere (previously it was the default on Windows only), which I believe fixes this. Is anyone able to test before I make a release?

**Comment by mochaaP** [comment]
This works for me (pipx 1.7.1, py 3.13.1 on linux)

**Comment by oconnor663** [comment]
Released as peru 1.3.3.
