### ISSUE TITLE
Option to import git repositories with .git file included

### ISSUE THREAD

**Issue by arecarn** [buildinspace/peru#75]
First, thank you for your hard work on peru it seems like a really cool project!

When I first used peru I expected that the .git folder to be imported along with it's corresponding git modules. That way I would be able to commit changes to the imported modules. 

I see the focus of this project is to include other people's code into a project, but I also think it could be a useful tool to combine different modules of your own code into a project and leaving the source control capabilities intact for each of the different modules.

Would it be possible to import git modules with the .git file included, or is there an existing method for being able to use source control on imported modules?

**Comment by oconnor663** [comment]
There is an existing method! Take a look at the `peru override` command. Say you have a module like this:

```yaml
git module foo:
   url: https://github.com/foo/foo
   rev: stable
```

And say you have your own clone of foo at `~/myfoo`. Then you can do this:

```
peru override add foo ~/myfoo
peru sync
```

Peru will use whatever is in `~/myfoo` as the contents of the foo module, instead of fetching from GitHub. This should let you work on your project and your dependencies at the same time. Note that peru is treating `~/myfoo` as a simple folder, not specifically as a git repo, so fields like `rev: stable` are ignored when you're using an override.

Does that work for the use case you had in mind?

The idea you described, where `peru sync` pulls metadata like `.git` into your project, has some tricky technical problems. The most immediate is that we use git trees internally to store all the files we fetch, and as it turns out, git *absolutely refuses* to represent anything named `.git` inside a tree. You can try it with low level commands like `git update-index`; it'll print `Ignoring path .git`. So even if we *wanted* to include `.git`, we might not be able to.

But there are a few reasons we might not want to also. One is that peru lets you mix multiple modules into the same directory. If two modules use git, then their `.git` folders will conflict even if none of their other files do. (Same applies to hg and svn.) Another reason is that we want `peru sync` to error out when fetched files are modified. That prevents us from deleting changes that might be important. It also helps us notice when we accidentally check in fetched files (because the next time you clone and sync, the sync will be an error).

**Comment by timdp** [comment]
@oconnor663 I'm trying to apply `override` to work on my project and its dependencies, as you describe.

Let's say I have two Git repositories and `repo2` is in `repo1`'s `peru.yaml`. I ran `peru override add repo2 /path/to/local/repo2` inside `repo1`.

Then, I created a new commit in the local `repo2`. Subsequently running `peru sync` there applied the changes from the commit to `repo1`'s copy of `repo2`, as I would expect. If I understand correctly, it basically just mirrored the files and didn't talk to Git at all.

I suppose that, to have `peru reup` actually store the `rev` from my local `repo2` in `repo1`'s `peru.yaml`, I need to push `repo2` first? Is there any other way to get the new commit's ID in there than manually editing `peru.yaml`?

**Comment by oconnor663** [comment]
@timdp you have it exactly right. Peru ignores the fact that your override path is a git repo, and it just copies the files that it sees there. `reup` is unaffected by `override`, and it will still talk to your regular git URL to find the latest master. So like you said, you either need to push your new commits upstream before you `reup`, or you need to edit `peru.yaml` by hand. (Though if you push the new `peru.yaml` before you push the commits it refers to, other people who don't have your override will hit an error when they sync. This is one of the reasons that `reup` ignores `override`.)

Does this feel like the right way to do things? I'd love to get feedback if this design is inconvenient or confusing.

Another approach that's useful sometimes, is to edit your `peru.yaml` to replace the `url` field in your module with `/path/to/local/repo2`. That will make peru treat your local repo like a real git repo, so it'll fetch `rev` instead of just whatever's checked out, and `reup` will actually read your local `master`. If you do that, you'll need to be careful not to check in your only-locally-meaningful repo path, in addition to unpublished commits like above. I've only ever really needed this for testing, but if it was something that a lot of people wanted, we could consider supporting something like `overrides.yaml`, where you could put local edits to module fields without actually touching `peru.yaml` (and then you could add `overrides.yaml` to `.gitignore`.) It's not clear to me that that's a good idea -- it would be very confusing if you created that file and then forgot about it, for example --but I'm curious what other people think.

**Comment by timdp** [comment]
Thanks.

I kind of like the idea of being able to override the repository location. It somewhat reminds me of `npm link`, which is one of the things I wanted to replace when I started looking into peru.

As you said, it could definitely get confusing. Some verbosity when running `sync` and `reup` could help though.
