### ISSUE TITLE
Automatic in-place override without caching for targeted module or all modules

### ISSUE THREAD

**Issue by jraygauthier** [buildinspace/peru#86]
Hi,

I was considering peru for my project. It seem pretty nice. However, I couldn't find any 
quick way to get a subset of modules described in the *.yaml file cloned directly to
their target location with their *.git (or *.hg) sub folder so that I can interract with
them.

I saw there is an override command but one has to clone his git / hg repository in
a separate step. This separate step seems superfluous most of the time as
the url mentioned in the *.yaml is exactly where I want to clone/pull/push from.

As a first step, it seem to me that it would greatly help if I could simply do
`peru override add --all` and have real clone put at their respective target locations using original url
for every module listed in the *.yaml file (hg, git, svn, etc; only the simple cases
where there are no complicated rules).

As a second step, it would be nice to be able to add modules to groups so
that the override command could target one or many groups (e.g.: `peru override add --group mygroup`).

It could also be nice to have a way to force using override from the *.yaml file systematically.

With these options, one can develop a package and its dependencies under the same
working directory and have all syncing deferred to peru (sync would stop on error).

Would there be any difficulties implementing theses enhancements?

**Comment by oconnor663** [comment]
There was some discussion of something similar in https://github.com/buildinspace/peru/issues/75. Here's an excerpt:

> The idea you described, where peru sync pulls metadata like .git into your project, has some tricky technical problems. The most immediate is that we use git trees internally to store all the files we fetch, and as it turns out, git absolutely refuses to represent anything named `.git` inside a tree. You can try it with low level commands like `git update-index`; it'll print `Ignoring path .git`. So even if we wanted to include `.git`, we might not be able to.

> But there are a few reasons we might not want to also. One is that peru lets you mix multiple modules into the same directory. If two modules use git, then their .git folders will conflict even if none of their other files do. (Same applies to hg and svn.) Another reason is that we want peru sync to error out when fetched files are modified. That prevents us from deleting changes that might be important. It also helps us notice when we accidentally check in fetched files (because the next time you clone and sync, the sync will be an error).

To clarify that last point, the point of "in-place overrides" would be so that you could make changes to your modules right there in the project. But if you then ran `peru sync`, it would notice that the files it owns have been modified. The behavior is then to quit with an error (default) or stomp on the modifications (with `--force`). If the modifications included new files that peru didn't know about, the result would be a mix of old and new.

So even if peru provided a command to help you get into this situation, you wind up in a situation where `peru sync` basically can't do anything until you `git clean -ffdx` your whole project. It might even be simpler to just make clones by hand and pretend that peru doesn't exist, until you're ready to start testing.

Having overrides "on the side" avoids this issue. It lets peru keep owning the files it placed on disk, and (this could be a benefit or a drawback) it means that you have the same `peru sync` workflow in your project that all your other users do. It also works better with features like `export`, where you only get a subdirectory of the module you're fetching.

All that said, I could definitely imagine peru adding a command that automates creating on-the-side overrides for you. (You could have a model where the git/hg/other big plugins know how to make a clone for you, but for plugins without explicit support for this concept you just get a regular file dump of the module.) Does that sound like it would be useful?

It would be super helpful to know more about your workflow. How important is it that you're hacking on dependencies in place?

**Comment by oconnor663** [comment]
I don't think I understood the ideas at the end of your comment. Could you tell me more about what you're thinking?

>As a second step, it would be nice to be able to add modules to groups so
that the override command could target one or many groups (e.g.: peru override add --group mygroup).

How do you imagine groups working in a normal situation? Is it like a separate `imports` tree with a name that works like another module?

>It could also be nice to have a way to force using override from the *.yaml file systematically.

Is the idea that if I clone your project and `peru sync`, I should get overrides automatically?

>With these options, one can develop a package and its dependencies under the same
working directory and have all syncing deferred to peru (sync would stop on error).

Help me understand that last bit; what is peru doing for you in this case?

**Comment by jraygauthier** [comment]
Hi,

we're actually splitting a huge svn repository in many git repository (one per library). We were looking
for a solution that would facilitate operations (at least clone / pull) over multiple repositories. During 
the transition, we will have the existing svn repository to manage as well. We had a look at google
*repo* which seem pretty nice as well but supports only git. 

So, as our dependencies are our own, we will always want to have the full repository access and not
a copy of its files. From what you said, as I understand it, peru would not be a solution for it. It seems
more suited at deployment and when you have a single project repository with multiple external
dependencies.

I was thinking that if peru was capable of automating the override process where overrides would
directly be placed in the working directory (not outside), it would be a very nice tool to bootrap a
project (internal + external dependencies). I understand that there were some design choices (which
is fine) that would complicate this workflow.

So I believe in our use case, the google *repo* workflow will be preferred (or maybe combination
of both). Thanks for this very complete answer. 

As an aside, I already brought peru to [nix](http://nixos.org/nix/) package manager. This should get
public once I get some time to get it approved as part of the official package manager packages
repositories. Can keep you notified if you wish.

**Comment by byrnedo** [comment]
Hi,

I'm in the same boat as you @jraygauthier, I wanted something that would allow us to bootstrap or even actively develop with, not just deploy. I'm not sure I grasp the full scope of the thread here but right now it seemed simpler to just use [mr](http://manpages.ubuntu.com/manpages/hardy/man1/mr.1.html).

**Comment by jraygauthier** [comment]
@byrnedo, thanks for the ref. I didn't know that `mr` tool. Will have a closer look.

**Comment by byrnedo** [comment]
No problem, I actually was only looking at google repo first too, I was 
told about 'mr' by a colleague, never came across it while searching for 
a tool to do this previously.
http://myrepos.branchable.com/ has some more info.

**Comment by oconnor663** [comment]
Thanks for the nix package! That sounds awesome. Please do keep me notified.

I think you have exactly the right idea for what we tried to do with peru. It's always been about handling *external* dependencies. I've always felt like two repos that are frequently edited together should really be one repo. With git on an SSD, I think that scales up to a few hundred thousand files, and beyond that Facebook has done some really cool work on making Mercurial go past a million. Do you know if either of those would be able to handle your case?

Now you've got me thinking though: What if we *had* designed peru to put clones in your project? Your workflow seems to be common, so I want to really think this one out. Here are some things that would change:

* Each module would have to have its own directory. No more combining multiple modules into a single dir. (Not a huge loss.)
* No more of what peru calls "rule fields", like `export`. Each repo would need to be imported in its entirety. (Something of a loss, though you can just invoke peru from a script that also copies/links stuff.)
* No more git-based tree cache. Each module could still have a plugin cache, basically an opaque directory for stashing stuff, and with git at least you could share `.git/objects` to get a lot out of that. `peru sync` would need to independently status each clone, though, which would be slower, but we could parallelize it.
* `peru reup` could still get updated metadata from the server, but it (or another command) could also look at what you've got locally.
* `peru override` would no longer need to exist.

This would make peru *very* similar to git submodules. It would still be able to talk to multiple different VCS types, which is something. It might also keep remote module definitions -- where you define one module solely for its `peru.yaml` file and then import other modules defined in there -- though no one uses that yet.

@jraygauthier and @byrnedo, maybe the question I should ask is why didn't you guys use regular git submodules?

**Comment by jraygauthier** [comment]
My pleasure for the package. Will keep you informed.

> why didn't you guys use regular git submodules?

For my part, because basically they come with many [pitfalls](https://www.google.ca/?gws_rd=ssl#q=why+git+submodules+are+bad) and are not meant
for our use case (sub modules would change too often for the workflow
being practical), do not work seamlessly with standard git command and are also
more limited in terms of supported vcs types.

In its actual incarnation, it seem from my POV that the `peru` is doing part
of the job done by a package manager such as `nix`. The package manager
will, for every dependency: fetch the sources, patch them, build them,  and install them. In
the case of `nix`, it even allows you to do so in sandboxes (on a per project basis).

`peru` is actually performing the fetching part and a kind of patching / reorganizing part.
A bit more tailored at a development setup (by default fetching latest for all) but without the 
hackability offered by other tools such as `repo`, `mr`, etc.

**Comment by oconnor663** [comment]
I do think of peru as a package manager, but one that doesn't have an install step. It seems weird to me that the major language-level package managers (gems, pip, npm) all work by installing packages in some kind of global-ish scope. If I can run my build without dropping files outside my project root, that feels cleaner.

There are some parts of git submodules I find really inexplicable (why doesn't `git checkout` update submodules by default?). But for the most part, I think that the trouble it runs into are due to the split-repo development model itself, and not just to the design of the submodules feature. Things like the "missing commit" problem, scattered logs, and unresolvable submodule merge conflicts. If peru tried to build in more support for the split-repo model, I think it would inevitably run into those issues too. Having One Big Repo for related projects avoids all of those problems, and peru is definitely designed with that approach in mind.

Please tell me more about the `repo` and `mr` hackability you mentioned, though. I haven't spend as much time as I should with either of those, so I have a lot to learn.

**Comment by byrnedo** [comment]
Can't really speak for peru, but mr has a .mrconfig file to describe the
repo relationships. Thing is you can also just define whatever command you
want in there too. So for example, if I wanted to support git flow in mr, I
just add it into the config:

[DEFAULT]
flow = git flow $@
[root]
checkout = git clone ssh://git@m <//git@shaun.xbookyq.se:7999>y.git.repo
/root.git
[root/⁠module1]
checkout = git clone ssh://git@ <//git@shaun.xbookyq.se:7999>my.git.repo/
module1.git
[root/⁠module1/submodule1]
checkout = git clone ssh://git@ <//git@shaun.xbookyq.se:7999>my.git.repo/sub
module1.git


Just to be clear, the `checkout` command is a built in, `mr` just requires
it to be defined since it could be svn, hg or whatever running.

From that point on I could type `mr flow init` in the root repo and it
would do it in all 3.

**Comment by jraygauthier** [comment]
>  It seems weird to me that the major language-level package managers (gems, pip, npm) all work by installing packages in some kind of global-ish scope.

I'm not sure about all of these other language level package manager tools, but using
*Haskell*, you have [Cabal Sandboxes](https://www.haskell.org/cabal/users-guide/installing-packages.html#developing-with-sandboxes) which you can use to create sandboxed
dev environment. Works on all platforms. It does allow hacking on depedencies as
well, but like *peru*, you have to register the sources for each one of these 
dependencies (`add-source` sub-command).

> Please tell me more about the repo and mr hackability you mentioned

What I meant by this is merely that as you get by default a proper clone / checkout of your
dependency in your workspace, you can start hacking right away on these dependencies
whether they be external or internal.

**Comment by oconnor663** [comment]
Got it. Python has `virtualenv`, which sounds like the Cabal Sandboxes you mentioned, and I know Ruby has something like that too, though I forget the name.

**Comment by questor** [comment]
+1  could a reverse-function for "override" help here like doing everything in reverse (moving modified sources back where override has taken them from?).
To give you more informations about my workflow and setup: I have an application (in an own repo) and in a subfolder called "extlibs" some libraries living in their own repos (for example I have a cube-rendering-app and in the extlibs-subfolder the graphic-library and the physics engine). now if I need something additional in a library I first add the api-using code in the app and later I enhance the library to handle the additional api-stuff needed by my application. and now I need to push my changes in the library back into the repo....

**Comment by oconnor663** [comment]
You probably know this but just to reiterate: the intended workflow for overrides is that you hack in the external repo that you're using as an override (probably side-by-side with your main project repo), and that your main project's build scripts call `peru sync` for you automatically. The main benefit of this over in-place hacking is that peru never gets confused about which files it owns vs which files contain your changes. Say you're working on your dependency, and then you `git checkout` to an older version of your project and run `peru sync`: if you're using overrides peru is happy to fetch old versions of other dependencies while maintaining your override, but if you've edited dependencies in-place peru will refuse to sync to avoid wiping out your changes.

I can see this getting annoying in at least a couple of circumstances. 1) If your project has no build step. Then it sucks to have to run `peru sync` every time you make changes. But it might make sense to sync from your test script or whatever. 2) You want to use your editor's fuzzy-finding smartness to hop between files in your project and files in dependencies, by setting the CWD of your editor to the root of your project. Side-by-side sucks for that.

If really want in-place editing, there are a couple things you can try: You can take the approach of just editing files directly in your project, and then using `cp -r` to bring your changes over to an actual clone when you're ready to commit them. (That's probably annoying, but it's functionally about the same as the "reverse override" you mentioned, @questor.) Or just drop an actual clone in-place in your repo and work with that. In both of those cases, `peru sync` will not work anymore, unless you use `--force`, in which case it'll clobber your changes. If you want to keep working in-place and keep using `peru sync` and you're willing to get *super fancy*, you can drop in a clone and use `peru override add` to make that clone *it's own* override -- you'll still need to use `--force` though, and there might be other confusing side-effects that I haven't thought of.

At the end of the day though, peru's just not designed with this workflow in mind. Peru wants `sync` to be a guarantee that you've got what you asked for in the `peru.yaml` file. Otherwise, it needs to be an error. There's not really a difference between the accidental changes that peru is trying to prevent, and the intentional changes that an in-place workflow makes. This goes with the general philosophy that if different projects are frequently changing together, as opposed to giving each other stable APIs, they should really live in one repository.

**Comment by oconnor663** [comment]
I'm going to close this one for now. I think at some point I'd like to write a script that reads `peru.yaml` and creates in-place close for all the modules there, for the times when that's easier to work with. That should be pretty simple to do, but I don't think peru itself should do it, because it's so different from how peru wants to operate normally. Let me know if anyone's interested in using such a script sooner rather than later.

**Comment by jck** [comment]
How about adding a config key called 'myrepos' or something like that. Peru could ensure that 'myrepos' are overridden and take care of pulling/pushing when syncing.

**Comment by oconnor663** [comment]
@jck If you mean something that lives in `peru.yaml`, we'd need to think about how that feature might work on a project with 20 different developers, where each dev works on a different part. If they all get the same `myrepos` config, would that work well for them? My guess is that you'd end up overriding all the dependencies all the time, to make it work for everyone, so it would probably make more sense to use [the actual `myrepos` tool](https://github.com/joeyh/myrepos) or something similar. (And if you feel the same way I do about source control, it would make the most sense to join all those repos into one.)

If you want to discuss this more, let's open a new issue.

**Comment by testing-in-chrome** [comment]
Have you looked at the chromium depot_tools? Please take a look at how [`gclient sync`](https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/master/gclient.py) works.

**Comment by oconnor663** [comment]
Yes, we had a little bit of experience with gclient and git submodules when we designed peru, and the differences in the design are on purpose.

**Comment by testing-in-chrome** [comment]
Even if it was purposely designed to be that way, I think a lot of developers (me included) would appreciate if `peru` supports checking out sub repos in-place in a way that enables us to contribute to the main and sub repos simultaneously. It's much more convenient and productive.

I honestly think this issue should be reopened so that it remains on the radar. It would be great if peru supports both workflows, and then developers can choose what suits them best.
