### ISSUE TITLE
parser error handling

### ISSUE THREAD

**Issue by questor** [buildinspace/peru#96]
the error handling of the parser should be improved, writing a rule like this:

rule test:
   pick bla

will result in a callstack without any information whats gone wrong (missing ":") (at least on windows, dunno behavior on linux). current parsing cursor would be helpful to find error in config file.

**Comment by questor** [comment]
btw, I had the impression that peru struggles with TABs.

**Comment by oconnor663** [comment]
Right now we use [PyYAML](https://bitbucket.org/xi/pyyaml) to parse the `peru.yaml` file. If the file fails to parse, in general all we can do is print the error that the parser gives us and quit. (That's why you're running into trouble with tabs: YAML [doesn't allow them](http://www.yaml.org/faq.html).

Trying the rule example you're mentioning though, I got this stacktrace:

```
Traceback (most recent call last):
  File "/home/jacko/bin/peru", line 18, in <module>
    peru.main.main()
  File "/home/jacko/peru/peru/main.py", line 161, in main
    Main().run(argv, env)
  File "/home/jacko/peru/peru/main.py", line 78, in run
    self.scope, self.imports = parse_file(self.runtime.peru_file)
  File "/home/jacko/peru/peru/parser.py", line 22, in parse_file
    return parse_string(f.read(), name_prefix)
  File "/home/jacko/peru/peru/parser.py", line 32, in parse_string
    return _parse_toplevel(blob, name_prefix)
  File "/home/jacko/peru/peru/parser.py", line 36, in _parse_toplevel
    modules = _extract_modules(blob, name_prefix)
  File "/home/jacko/peru/peru/parser.py", line 103, in _extract_modules
    yaml_name)
  File "/home/jacko/peru/peru/parser.py", line 109, in _build_module
    peru_file = blob.pop('peru file', DEFAULT_PERU_FILE_NAME)
AttributeError: 'str' object has no attribute 'pop'
```

That's super unhelpful! It looks like what's happening is that, by omitting the colon, you unintentionally turned a map into a string. If you had had further fields it would've been a genuine parse error, but unfortunately it's still valid YAML. So peru starts trying to treat the contents of your rule like a dictionary, and we get this `AttributeError`. We should definitely do some explicit typechecking to prevent this error. Marking as a bug. Thanks for the report.

**Comment by oconnor663** [comment]
Diff up to fix this particular error: https://phabricator.buildinspace.com/D204

**Comment by questor** [comment]
great, thanks :)
